spring.application.name=springdev
server.port=30001
server.address=0.0.0.0
#DataBase Connection Settings
spring.datasource.url=${spring_datasource_url:jdbc:h2:mem:localdb}
spring.datasource.username=${spring_datasource_username:sa}
spring.datasource.password=${spring_datasource_password:}
spring.datasource.driver-class-name=${spring_datasource_driver_class_name:org.h2.Driver}
spring.datasource.hikari.maximum-pool-size=${spring_datasource_hikari_maximum_pool_size:10}

# ======= H2 Console ?? =======
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#JPA Settings
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
#N+1 -> Batch_size??
#spring.jpa.properties.hibernate.default_batch_fetch_size=3

#Tomcat-Thread-Limit
#Try Virtual Thread
#server.tomcat.threads.max=1


#Mybatis Settings
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=app.springdev.excel.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.cache-enabled=false
logging.level.org.mybatis=DEBUG
logging.level.jdbc.sqlonly=DEBUG
logging.level.jdbc.sqltiming=DEBUG
logging.level.org.apache.ibatis.executor.BatchExecutor=DEBUG


#Front-Mustache
spring.mustache.prefix=classpath:/templates/
spring.mustache.suffix=.mustache
spring.mustache.charset=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
#multipart
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#Actuator & Prometheus Setting
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

# Config
spring.profiles.active=local
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://gaebabja:1234@localhost:20001}

#Logging
logging.level.root=INFO
logging.level.org.hibernate=ERROR
#logging.level.org.springframework=ERROR
logging.level.com.zaxxer.hikari=ERROR
#logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=ERROR
logging.level.app.springdev.elastic.datasync.outbox.rabbit.scheduler = ERROR

#Redis
#Desc : Docker Redis network : network-dev ,using Dns

spring.data.redis.connect-timeout=1000
spring.data.redis.client-type=lettuce
spring.data.redis.repositories.enabled=false
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PWD:1234}

#Session
server.servlet.session.cookie.name=JSESSIONID
spring.session.redis.namespace=myapp:session
spring.session.store-type=redis

#Elastic
spring.elasticsearch.uris=localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=changeme
spring.elasticsearch.connection-timeout=1s
logging.level.org.elasticsearch=INFO
logging.level.org.elasticsearch.client=DEBUG
logging.level.org.springframework.data.elasticsearch=DEBUG

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=1234
spring.rabbitmq.virtual-host=/
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

#Scheduler Activation
scheduler.outbox-processor.enabled=false
scheduler.outbox-relay.enabled=true